In [1]:
from scipy import stats
dirichlet = stats.dirichlet([1, 2, 3, 4])
num_samples = 5
print('Generating', num_samples, 'samples:')
samples = dirichlet.rvs(size=num_samples)
print(samples)
print('Sum of each sample (should be 1):')
print(samples.sum(axis=1))
print('Value of probability density function at each sample:')
print(dirichlet.pdf(samples.transpose()))





Generating 5 samples:
[[0.03332407 0.16573515 0.23410797 0.5668328 ]
 [0.07772001 0.2080105  0.41587145 0.29839804]
 [0.07036074 0.50489903 0.15306046 0.27167977]
 [0.00111819 0.18627113 0.27037297 0.5422377 ]
 [0.13461098 0.12858577 0.37365585 0.3631474 ]]
Sum of each sample (should be 1):
[1. 1. 1. 1. 1.]
Value of probability density function at each sample:
[50.02576742 28.905012    7.17272649 65.64823185 25.99962527]


In [3]:
import pandas as pd
data = pd.read_csv('socialmobility.csv')
data

father           son  count
0           farm          farm    703
1           farm     unskilled   1478
2           farm       skilled   1430
3           farm  professional   1109
4      unskilled          farm     58
5      unskilled     unskilled   1756
6      unskilled       skilled   1630
7      unskilled  professional   1568
8        skilled          farm     63
9        skilled     unskilled   1453
10       skilled       skilled   2068
11       skilled  professional   2483
12  professional          farm     61
13  professional     unskilled    749
14  professional       skilled   1183
15  professional  professional   3315

In [44]:
ones=[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]
count = list(data['count'])

dirichlet_prior = stats.dirichlet(ones)
p_hyperparameters = [ones[i] + count[i] for i in range(0,16)] #dirichlet posterior hyperparameters = alpha + count per class
dirichlet_posterior = stats.dirichlet(p_hyperparameters)
samples = dirichlet_posterior.rvs(size=10000)
#print(samples)

#Question 5 answers
question_1 =samples[4:8]
question_2 = samples[3]

ci_1 = np.percentile(question_1, 2.5), np.percentile(question_1, 97.5)
ci_2 = np.percentile(question_2, 2.5), np.percentile(question_2, 97.5)
print(ci_1,'\n',ci_2)

(0.0025200349326895332, 0.1553795961958522) 
 (0.002574614035752829, 0.14062729226353032)


In [ ]:
def build_dirichlet_posterior(count_vec):
    alpha = np.ones_like(count_vec)
    prior = dirichlet(alpha=alpha)
    #new_alpha = alpha + sum(count_vec)
    new_alpha = [alpha[i] + count_vec[i] for i in range(len(count_vec))]
    print('new alpha:', new_alpha)
    posterior = dirichlet(alpha=new_alpha)
    return posterior

In [ ]:
#son skilled | father unskilled
size = 10**6
counts = df['count'].values
posterior = build_dirichlet_posterior(counts[4:8])
samp = posterior.rvs(size=size)
np.percentile(samp[:,2], [2.5, 97.5])

In [ ]:
#father farm | son professional
size = 10**6
posterior = build_dirichlet_posterior([counts[3], counts[7], counts[11], counts[15]])
samp = posterior.rvs(size=size)
np.percentile(samp[:,0], [2.5, 97.5])